services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
      # Override run command
    command: pnpm run start:dev reservations
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
